apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpw-aks-demo-app
  labels:
    app: kpw-aks-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kpw-aks-demo-app
  template:
    metadata:
      labels:
        app: kpw-aks-demo-app
    spec:
      containers:
        - name: app
          image: ghcr.io/natthakritc/kpw-aks-trn-lab:latest
          ports:
            - containerPort: 80
