apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpw-aks-demo-app
  namespace: ncd
  labels:
    app: kpw-aks-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kpw-aks-demo-app
  template:
    metadata:
      labels:
        app: kpw-aks-demo-app
    spec:
      containers:
        - name: app
          image: ghcr.io/natthakritc/kpw-aks-trn-lab:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kpw-aks-demo-app
  namespace: ncd
spec:
  selector:
    app: kpw-aks-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP #LoadBalancer #  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kpw-aks-demo-app
  namespace: ncd
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
    - http:
        paths:
          - path: /poc
            pathType: Prefix
            backend:
              service:
                name: kpw-aks-demo-app
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kpw-aks-demo-app
                port:
                  number: 80

# First version of Ingress, without path-based routing
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: kpw-aks-demo-app
#   namespace: ncd
# spec:
#   ingressClassName: webapprouting.kubernetes.azure.com
#   rules:
#     - http:
#         paths:
#           - backend:
#               service:
#                 name: kpw-aks-demo-app
#                 port:
#                   number: 80
#             path: /
#             pathType: Prefix
