apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpw-aks-demo-app
  namespace: ncd
  labels:
    app: kpw-aks-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kpw-aks-demo-app
  template:
    metadata:
      labels:
        app: kpw-aks-demo-app
    spec:
      containers:
        - name: app
          image: ghcr.io/natthakritc/kpw-aks-trn-lab:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kpw-aks-demo-service
  namespace: ncd
spec:
  selector:
    app: kpw-aks-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
